### ISSUE TITLE
Unexpected leading zero

### ISSUE THREAD

**Issue by tuck0066** [tuck0066/kraken-good-accessibility#1]
@Chelle Lorenzen

DLed markbot again.  It is whriling around in circles and won't stop and has given me this new error. 

![Screenshot (589)](https://user-images.githubusercontent.com/70998021/95619724-0c440800-0a3d-11eb-9292-c5a06a1bba4a.png)

**Comment by tuck0066** [comment]
@hellachella 

Line 90 error

**Comment by hellachella** [comment]
Yes, this is line 90 of your CSS and not the HTML. Change `padding: 0.5rem;` to `padding: .5rem;`
